### ISSUE TITLE
keyless ips getting parsed as keys

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/api-traffic-processors#34]
this is ok, but currently its only happening on the apiaxle side. maybe we should log ips for keyless usage from fastly as well.

**Comment by sleepylemur** [comment]
@rmarianski think should we deal with this now or wait until v1 tiles have been released?

**Comment by rmarianski** [comment]
In the fastly logs table in redshift, we don't need to capture the ip address. I'd prefer to just leave it out if possible.
