### ISSUE TITLE
Update log parsing for xonacatl

### ISSUE THREAD

**Issue by rmarianski** [mapzen/api-traffic-processors#48]
Xonacatl is making subrequests back into fastly. We should not double count these requests. Xonacatl is passing a request header that can be used to distinguish these requests.

**Comment by sleepylemur** [comment]
it looks like either xonacatl or just vector-tiles 1.0 is messing up the x-forwarded-for header, which apiaxle relies on for rate limiting keyless requests.

**Comment by rmarianski** [comment]
Nice catch! The x-forwarded-for header logic has been updated in dev and prod in the fastly vcl.

**Comment by sleepylemur** [comment]
@rmarianski is this closable? did we finish everything here?
