### ISSUE TITLE
Logs from Routing, Matrix, and Elevation

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/api-traffic-processors#53]
@migurski what do you think about adding path and query columns to api_hits? that way there'd be basic regex searchability into all services, and there's nothing that needs updating if people's url schemes change.
if we decide we need easier querying we can always add in custom service tables on a case by case basis.

cc: @kdiluca

**Comment by migurski** [comment]
Path columns would be great! Query columns might be weird-as-in-huge; anything to worry about these? If we're adding stuff, the Referer header would be interesting.

**Comment by sleepylemur** [comment]
I was thinking to put a conservative limit on the query size. Some apis (like pelias) have all the info in the query whereas others (like tiles) encode most of it in the path. Unfortunately the way apiaxle is setup to log to redshift, we don't have access to request headers :(

**Comment by sleepylemur** [comment]
new plan:
create mobility table with ts, api, key, status, path, query
send in data that hits valhalla, matrix, and elevation

**Comment by sleepylemur** [comment]
Request from @migurski : trim leading `?` from query field.
